### ISSUE TITLE
Landing Page para o projeto Ganhando XP

### ISSUE THREAD

**Issue by ogiansouza** [GanhandoXP/frontend#1]
## Descrição do projeto

Landing Page para o projeto Ganhando XP

## Tecnologias

- HTML
- CSS
- JavaScript
- ...

## Prazo do projeto

Aberto

## Meu perfil e equipe que procuro

Me chamo Gian Souza, estudante de análise e desenvolvimento de sistemas, atuo há três anos como desenvolvedor front-end,.

Procuro para o projeto um desenvolver iniciante que queira me ajudar e aprender.

**Comment by viniciusmeneses** [comment]
Gostaria de participar e ajudar a desenvolver a Landing Page, caso queira minha ajuda é só falar!

**Comment by ogiansouza** [comment]
Valeu @viniciusmeneses vou entrar em contato contigo
